adService:
  create: true
  name: adservices # Changed name to trigger ImgPullErr 
  # resources:
  #   requests:
  #     cpu: 200m
  #     memory: 180Mi
  #   limits:
  #     cpu: 300m
  #     memory: 300Mi

cartService:
  # create: true
  # name: cartservice
  # resources:
  #   requests:
  #     cpu: 200m
  #     memory: 128Mi
    limits:
      cpu: 300m
      memory: "60Mi" # Reduced from 128Mi to trigger OOM during startup 
