adService:
  create: true
  name: adservices # This change works because 'name' is a top-level key under adService
  # resources:
  #   requests:
  #     cpu: 200m
  #     memory: 180Mi
  #   limits:
  #     cpu: 300m
  #     memory: 300Mi

cartService:
  # create: true
  # name: cartservice
  resources:  # <--- You were missing this vital parent key
    # requests:
    #   cpu: 200m
    #   memory: 128Mi
    limits:
      cpu: 300m
      memory: "8Mi" # Reduced from 256Mi to trigger OOM during startup 
